### PR TITLE
Fix regexp might get infinite loop

### PR DESCRIPTION
**Pull request by jackycute**
Which cause by alter the regex lastIndex in the function ([here](https://github.com/markdown-it/markdown-it-abbr/blob/master/index.js#L126)).
And fix by check if the lastIndex same as the regex index.

Thx.

### CODE REVIEW

**Comment by rlidwka** [comment]
Looks good to me, I see a theoretical possibility of a infinite loop there as well. However, I can't quite figure out how to write a test for this.

Do you have an example of a `markdown-it` input that will cause an infinite loop here?

**Comment by jackycute** [comment]
Hi @rlidwka,
Yeah, I never think of this possibility until it happened on one of my user's doc.
I can't very sure about this case, let me try to figure it out.

**Update after another day**
I found it, it might be bug or some.
When you use it with empty abbr reference (invalid) with emphasis syntax, will go into it.
Also the following whitespace will be replace out, too..

Example:
```
Anything with **this** and **that**.

*[]: and will cause infinite loops
```

Can be reproduce even in here: https://markdown-it.github.io/
I could open an issue if you need

Thanks for your guys hard work.

**Comment by rlidwka** [comment]
I checked how other implementations (namely, php markdown extra) process empty abbreviations. Looks like allowing those is a bug in itself.

Fixed, now `*[]:` is no longer treated as a valid abbreviation.

Thanks for reporting!

**Comment by jackycute** [comment]
Thanks @rlidwka

**Pull request closed without merging**
